### ISSUE TITLE
queryParams differ from pretender implementation

### ISSUE THREAD

**Issue by mrloop** [miragejs/mirage-msw#1]
I've got a serializer for organizations which can include memberships. An API request in the tests can look like

```
http://api.dev.qonto.co/v3/organizations?includes%5B%5D=memberships&per_page=200&user_id=dafeff4f-34fb-49b0-bf60-5a7db77fa4fc&with%5B%5D=label_lists&with%5B%5D=labels
```

The [request](https://miragejs.com/api/classes/serializer/#serialize) arguments `queryParams` when using pretender looks like
```
{
  includes: ["memberships"],
  per_page: "200",
  user_id: "a91ac577-76bc-4932-9dfa-a3a4d7cacbe0",
  with: ["label_lists","labels"]
}
```

Using `mirage-msw`
```
{
  includes[]: "memberships",
  per_page: "200",
  user_id: "dafeff4f-34fb-49b0-bf60-5a7db77fa4fc",
  with[]: "labels"
}
```

**Comment by cah-brian-gantzler** [comment]
Will take a look at that. I thought it was was the same basic code doing serialization in both cases, but I might have missed something. 

Feel free to make a PR if you find it before I get to it

**Comment by cah-brian-gantzler** [comment]
I think I might need a little more information or a repo producing the problem. Where (in code) are you looking to see the queryParams difference. In the pretender config https://github.com/bgantzler/mirage-pretender/blob/master/lib/pretender-config.js I see no reference to it doing anything with query params. In MSW config https://github.com/bgantzler/mirage-msw/blob/master/lib/msw-config.js#L38 I do something with queryParams, but I dont remember why without debugging the code again :), although I dont see just looking at it why it would add `[]` to the end of a property.

Its possible it could be in MSW itself, but will have to debug it to see if its this repo or MSW.

Implementations are definitely different when it comes to a property containing an array in queryParams. I have an issue where ember data is serilalizing it one way and my back end (spring) doesnt like it and wants a different way. Everything works but serializing arrays. Current suggestion is to write my own adapter which seems overkill to customize one thing.

**Comment by mrloop** [comment]
I think ideally would want a common suite of tests to run against all the different interceptor packages, something like  https://github.com/bgantzler/mirage-pretender/pull/3 . And then add tests to check that similar arguments to miragejs for instance the queryParams in the request object passed to [serialize](https://miragejs.com/api/classes/serializer/#serialize) looks the same.

For this specific issue pretty sure its somewhere here https://github.com/bgantzler/mirage-msw/blob/master/lib/msw-config.js#L39.  But before creating a PR I'd want to write test that passed against `mirage-pretender` first, then could verify fix by running `mirgate-msw` against the same test suite.

**Comment by cah-brian-gantzler** [comment]
Pretender must handle the query params before calling the route, in the MSW version the route handler is very different and I have to translate to the version that pretender does. This works for simple query params but NOT for arrays as you have noticed. The translation of code is here https://github.com/bgantzler/mirage-msw/blob/master/lib/msw-config.js#L38. So yea, that loop has to be a lot smarter, detect arrays in the query params and translate them accordingly to the pretender version. 

I see and understand the problem. Will try to get a version working soon. 

Thanks for the feedback

**Comment by cah-brian-gantzler** [comment]
I have created a branch `fix-array-params` that should fix your issue. Let me know if that does it an does not cause any other issues, Ill merge it in.

**Comment by mrloop** [comment]
Thanks, `fix-array-params` fixes this issue

**Comment by cah-brian-gantzler** [comment]
Cool, I will merge it into master.

There is a pending fix in mirage that will break this repo. If you update mirage will have to update this as well at same time.

Waiting on the mirage release before I merge in this repo to allow me to put out this kind of fix easier

**Comment by cah-brian-gantzler** [comment]
I have merged that into master and pushed a version `0.1.0` out to npm.

**Comment by cah-brian-gantzler** [comment]
There was a change pending in MirageJS that was released in 0.1.46. So this repo version 0.1.0 only works with 0.1.45. I just published 0.1.1 of this repo that now works with 0.1.46 os MirageJS. 

If you want to upgrade MirageJS to 0.1.46 you have to upgrade this lib to 0.1.1

On a side note. How has MSW with Mirage been working out for you?

**Comment by mrloop** [comment]
I've not made time to work on it, other commitments have got in the way. There are a couple of issues I need to resolve to be able to use mirage-msw, got more time available coming up to work on it.

**Comment by mrloop** [comment]
Doing some work on migrating test suite today. Issues I've encountered
1. Need to do `request.url.toString()` as now `request.url` returns a `URL`
2. The request headers need to be handled differently before did `request.requestHeaders` now I'm doing `let requestHeaders = request.requestHeaders || request.headers.raw();` 
3. form-data handling is different, need access to the msw request MockedRequest, see https://github.com/bgantzler/mirage-msw/pull/4

Issue 1. and 2. are handled in the mirage handlers. Issue 3. needs the update in the MR. 

I'm hopeful there's not much more to do after this for a total of ~382~ _405_ mirage endpoints (I forgot `DELETE`)

**Comment by cah-brian-gantzler** [comment]
Not sure I understand #3 or following how the PR would actually make that happen

**Comment by mrloop** [comment]
Closing this as the original issue is fixed
