### ISSUE TITLE
Add docs on how to setup

### ISSUE THREAD

**Issue by jasikpark** [miragejs/mirage-msw#5]
How can I setup this library as the MirageJS interceptor? Judging from https://github.com/bgantzler/mirage-pretender/tree/master, I should import the default import and then pass it to the MirageJS server config?

```ts
import { createServer } from "miragejs"
import MSWInterceptor from 'mirage-msw';

export default function () {
  createServer({
    interceptor: new MSWInterceptor(),  
    routes() {
      this.get("/api/reminders", () => ({
        reminders: [],
      }))
    },
  })
}
```

is MSW a drop-in solution, or am I doing something else wrong?:

<img width="636" alt="image" src="https://github.com/bgantzler/mirage-msw/assets/10626596/90ce6bf1-9c6d-4ca4-9f70-779c238d9827">

**Comment by cah-brian-gantzler** [comment]
Yes, it should be a drop in replacement. 

Looking at the code, args should be an array, which it appears to not be for you. Could you put a breakpoint at the line its failing on and see what args is?

This code https://github.com/bgantzler/mirage-msw/blob/master/lib/msw-config.js#L87 creates the array of all parameters not the path, "/api/reminders" in your case. Even is there is only one param, you should get an array of one, your function. If its undefined, its almost as if your function is NOT being passes to the method. 
Your function does has an extra set of parens, but I think that should work. Have you tried the following just in case?

```
routes() {
      this.get("/api/reminders", () => {
        reminders: [],
      })
    },
```

**Comment by cah-brian-gantzler** [comment]
or maybe
```
routes() {
      this.get("/api/reminders", () => {
            return {
                 reminders: [],
            };
       });
    },
```

If that works then its more about what is the abbreviated version. Since braces usually make the beginning of the function, the one I posted is probably incorrect. So I see why you added the extra parens, but it might be mis parsing that.

**Comment by cah-brian-gantzler** [comment]
Yea sorry, cant believe there isnt a readme.

**Comment by IanVS** [comment]
Added a readme.
