### ISSUE TITLE
Bug: mirage-msw no longer respects `timing` config value

### ISSUE THREAD

**Issue by jasikpark** [miragejs/mirage-msw#6]
I think that https://github.com/bgantzler/mirage-msw/pull/3 may have overriden https://github.com/bgantzler/mirage-msw/commit/fb7c90798fa7cd7582069b78a74b31642c0422ca, since there is no longer an explicit translation between `timing` and `delay`?

I'd be happy to submit a pull request, if you can point me in how I might fix things.

I'm seeing `mirage-msw` not respect my set server timings from an initial config setup.

**Comment by jasikpark** [comment]
orr.... i can't read

https://github.com/bgantzler/mirage-msw/blob/13c0b4d597534927fa5edf5d9d5aae85ddfc2d9c/lib/msw-config.js#L115

i'm still unsure about my timings setup, since it's using a timing of `0` atm.

**Comment by cah-brian-gantzler** [comment]
From the code you posted the timing is being passed into MSW. If for some reason that is not working as expected, may have to open an issue with MSW itself

**Comment by jasikpark** [comment]
it is working as intended, but this.timing is always set to 0 currently, removing the setting makes the delay work with the MSW default

**Comment by cah-brian-gantzler** [comment]
Yes I believe there was code somewhere when mirageJS was setting 0 as false, ie no timing override, when it should have set undefined, because other code it picking that 0 as an intentional 0.

**Comment by jasikpark** [comment]
> Yes I believe there was code somewhere when mirageJS was setting 0 as false, ie no timing override, when it should have set undefined, because other code it picking that 0 as an intentional 0.

Probably https://github.com/miragejs/miragejs/pull/1080 needs to be merged, I suppose?

**Comment by rmjohnson-olo** [comment]
@jasikpark just wanted to let you know that https://github.com/miragejs/miragejs/pull/1080 has been merged and it looks like has been released with https://github.com/miragejs/miragejs/releases/tag/v0.1.48 🎉

**Comment by IanVS** [comment]
I think this is no longer a problem in this package.
